language: elixir

elixir:
  - '1.9.1'

otp_release:
  - '22.0.4'

sevices:
  - docker

stages:
  - test
  - build
  - name: push
    if: branch == docker-push

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: 
        - mix deps.get
        - mix test

    - stage: build
      name: "Docker Build"
      script:
        - docker build -t ebostijancic/mini_repo --no-cache .

    - stage: push
      name: "Push docker image"
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push ebostijancic/mini_repo

      

