language: elixir

elixir:
  - '1.9.1'

otp_release:
  - '22.0.4'

sevices:
  - docker

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: 
        - mix deps.get
        - mix test
    - stage: "Docker"
      name: "Docker Build"
      script:
        - docker build -t ebostijancic/mini_repo --no-cache .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push ebostijancic/mini_repo
      

